-- MySQL Script generated by MySQL Workbench
-- Fri Jul  3 13:56:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `new_db` ;

-- -----------------------------------------------------
-- Table `new_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db`.`address` (
  `city_id` VARCHAR(3) NOT NULL,
  `city_name` VARCHAR(45) NOT NULL,
  `state_name` VARCHAR(45) NOT NULL,
  `pincode_num` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `city_name` (`city_name` ASC) INVISIBLE,
  UNIQUE INDEX `pincode_num` (`pincode_num` ASC) INVISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `new_db`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db`.`attendance` (
  `staff_emp_id` VARCHAR(11) NOT NULL,
  `on_date` DATE NOT NULL,
  `date_status` CHAR(1) NOT NULL,
  PRIMARY KEY (`on_date`, `staff_emp_id`),
  INDEX `fk_attendance_staff1_idx` (`staff_emp_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
KEY_BLOCK_SIZE = 2;


-- -----------------------------------------------------
-- Table `new_db`.`technology`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db`.`technology` (
  `skill_id` VARCHAR(2) NOT NULL,
  `skill_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`skill_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `new_db`.`attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db`.`attribute` (
  `attributecol` INT NOT NULL AUTO_INCREMENT,
  `staff_emp_id` VARCHAR(11) NOT NULL,
  `technology_skill_id` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`attributecol`),
  INDEX `fk_attributes_staff_idx` (`staff_emp_id` ASC) VISIBLE,
  INDEX `fk_attribute_technology_idx` (`technology_skill_id` ASC) VISIBLE,
  CONSTRAINT `fk_attribute_technology`
    FOREIGN KEY (`technology_skill_id`)
    REFERENCES `new_db`.`technology` (`skill_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `new_db`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db`.`contact` (
  `staff_emp_id` VARCHAR(11) NOT NULL,
  `phone_num` VARCHAR(10) NOT NULL,
  `email_addr` VARCHAR(45) NOT NULL,
  `home_addr` VARCHAR(60) NOT NULL,
  `address_city_id` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`staff_emp_id`),
  UNIQUE INDEX `phone_num` (`phone_num` ASC) VISIBLE,
  UNIQUE INDEX `email_addr` (`email_addr` ASC) VISIBLE,
  UNIQUE INDEX `home_addr` (`home_addr` ASC) VISIBLE,
  INDEX `fk_contact_staff_idx` (`staff_emp_id` ASC) VISIBLE,
  INDEX `fk_contact_address_idx` (`address_city_id` ASC) VISIBLE,
  CONSTRAINT `fk_contact_address`
    FOREIGN KEY (`address_city_id`)
    REFERENCES `new_db`.`address` (`city_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `new_db`.`designation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db`.`designation` (
  `role_id` VARCHAR(10) NOT NULL,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_name` (`role_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `new_db`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db`.`staff` (
  `emp_id` VARCHAR(11) GENERATED ALWAYS AS (upper(concat(substr(`first_name`,1,1),substr(`birth_date`,3),substr(`last_name`,1,2)))) STORED,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `pass` VARCHAR(20) NOT NULL,
  `designation_role_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`emp_id`),
  INDEX `fk_staff_designation_idx` (`designation_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_designation_idx`
    FOREIGN KEY (`designation_role_id`)
    REFERENCES `new_db`.`designation` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
